#pragma config(Motor,  motor1,          leftFrontDrive, tmotorVexIQ, PIDControl,reversed, encoder)
#pragma config(Motor,  motor2,          leftRearDrive, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          rightFrontDrive, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          rightRearDrive, tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* ---------------------------------------------------------------------------
 ** small-manual.c
 ** Skeleton class for the manual remote control code.
 **
 ** Author: James Taylor & Keith Tiemann
 ** -------------------------------------------------------------------------*/

int SERVO_SPEED = 63;

task main() {
	int threshold = 20;
	while (true) {
		if (vexRT[Ch3] > threshold || vexRT[Ch3] < -threshold) {
			motor[leftMotor] = vexRT[Ch3];
		} else {
			motor[leftMotor] = 0;
		}
		if (vexRT[Ch2] > threshold || vexRT[Ch2] < -threshold) {
			motor[rightMotor] = vexRT[Ch2];
		} else {
			motor[rightMotor] = 0;
		}
		if (vexRT[Btn6U] == 1) {
			motor[liftMotor] = SERVO_SPEED;
		} else if (vexRT[Btn6D] == 1) {
			motor[liftMotor] = -SERVO_SPEED;
		} else {
			motor[liftMotor] = 0;
		}
		if (vexRT[Btn5U] == 1) {
			motor[armMotor] = SERVO_SPEED;
		} else if (vexRT[Btn5D] == 1) {
			motor[armMotor] = -SERVO_SPEED;
		} else {
			motor[armMotor] = 0;
		}
	}
}
